/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrefectureSlugRouteImport } from './routes/$prefectureSlug'
import { Route as IndexRouteImport } from './routes/index'

const PrefectureSlugRoute = PrefectureSlugRouteImport.update({
  id: '/$prefectureSlug',
  path: '/$prefectureSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$prefectureSlug': typeof PrefectureSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$prefectureSlug': typeof PrefectureSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$prefectureSlug': typeof PrefectureSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$prefectureSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$prefectureSlug'
  id: '__root__' | '/' | '/$prefectureSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrefectureSlugRoute: typeof PrefectureSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$prefectureSlug': {
      id: '/$prefectureSlug'
      path: '/$prefectureSlug'
      fullPath: '/$prefectureSlug'
      preLoaderRoute: typeof PrefectureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrefectureSlugRoute: PrefectureSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
