/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as MapRouteImport } from './routes/map'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as PrefectureIndexRouteImport } from './routes/prefecture/index'
import { Route as WatchlistListIdRouteImport } from './routes/watchlist/$listId'
import { Route as PrefecturePrefectureSlugRouteImport } from './routes/prefecture/$prefectureSlug'
import { Route as DamDamIdRouteImport } from './routes/dam/$damId'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefectureIndexRoute = PrefectureIndexRouteImport.update({
  id: '/prefecture/',
  path: '/prefecture/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistListIdRoute = WatchlistListIdRouteImport.update({
  id: '/watchlist/$listId',
  path: '/watchlist/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefecturePrefectureSlugRoute =
  PrefecturePrefectureSlugRouteImport.update({
    id: '/prefecture/$prefectureSlug',
    path: '/prefecture/$prefectureSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DamDamIdRoute = DamDamIdRouteImport.update({
  id: '/dam/$damId',
  path: '/dam/$damId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/today': typeof TodayRoute
  '/dam/$damId': typeof DamDamIdRoute
  '/prefecture/$prefectureSlug': typeof PrefecturePrefectureSlugRoute
  '/watchlist/$listId': typeof WatchlistListIdRoute
  '/prefecture/': typeof PrefectureIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/today': typeof TodayRoute
  '/dam/$damId': typeof DamDamIdRoute
  '/prefecture/$prefectureSlug': typeof PrefecturePrefectureSlugRoute
  '/watchlist/$listId': typeof WatchlistListIdRoute
  '/prefecture': typeof PrefectureIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/today': typeof TodayRoute
  '/dam/$damId': typeof DamDamIdRoute
  '/prefecture/$prefectureSlug': typeof PrefecturePrefectureSlugRoute
  '/watchlist/$listId': typeof WatchlistListIdRoute
  '/prefecture/': typeof PrefectureIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/map'
    | '/today'
    | '/dam/$damId'
    | '/prefecture/$prefectureSlug'
    | '/watchlist/$listId'
    | '/prefecture/'
    | '/watchlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/map'
    | '/today'
    | '/dam/$damId'
    | '/prefecture/$prefectureSlug'
    | '/watchlist/$listId'
    | '/prefecture'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/map'
    | '/today'
    | '/dam/$damId'
    | '/prefecture/$prefectureSlug'
    | '/watchlist/$listId'
    | '/prefecture/'
    | '/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  MapRoute: typeof MapRoute
  TodayRoute: typeof TodayRoute
  DamDamIdRoute: typeof DamDamIdRoute
  PrefecturePrefectureSlugRoute: typeof PrefecturePrefectureSlugRoute
  WatchlistListIdRoute: typeof WatchlistListIdRoute
  PrefectureIndexRoute: typeof PrefectureIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefecture/': {
      id: '/prefecture/'
      path: '/prefecture'
      fullPath: '/prefecture/'
      preLoaderRoute: typeof PrefectureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/$listId': {
      id: '/watchlist/$listId'
      path: '/watchlist/$listId'
      fullPath: '/watchlist/$listId'
      preLoaderRoute: typeof WatchlistListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefecture/$prefectureSlug': {
      id: '/prefecture/$prefectureSlug'
      path: '/prefecture/$prefectureSlug'
      fullPath: '/prefecture/$prefectureSlug'
      preLoaderRoute: typeof PrefecturePrefectureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dam/$damId': {
      id: '/dam/$damId'
      path: '/dam/$damId'
      fullPath: '/dam/$damId'
      preLoaderRoute: typeof DamDamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  MapRoute: MapRoute,
  TodayRoute: TodayRoute,
  DamDamIdRoute: DamDamIdRoute,
  PrefecturePrefectureSlugRoute: PrefecturePrefectureSlugRoute,
  WatchlistListIdRoute: WatchlistListIdRoute,
  PrefectureIndexRoute: PrefectureIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
